### ISSUE TITLE
[Bug]: ,da true 在账户为非管理员的群组中，并不能删除所有该账户在该群组发出的消息，尤其是一个月前左右的消息。

### ISSUE THREAD

**Issue by opuses114514** [TeamPGM/PagerMaid-Pyro#21]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [ ] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

1.0.9

### 运行环境

Linux

### 重现步骤

准备一个在某大群至少有五个月发言记录的账户，在与发言所用设备不同的设备上执行,da true。清除缓存后在该群通过根据用户查找聊天记录，发现仍有消息未删除。

### 期望的结果是什么？

执行 ,da true 后无法根据用户查找到任何聊天记录。

### 实际的结果是什么？

执行 ,da true 后能根据用户查找到部分聊天记录。

### 日志记录（可选）

```python3
在那些仍能根据用户搜索到聊天记录的群组中执行 ,da true 无任何日志反馈
```

**Comment by omg-xtao** [comment]
@opuses114514 请使用 selfprune 999999
