### ISSUE TITLE
[Bug]: docker compere、

### ISSUE THREAD

**Issue by ptsa** [TeamPGM/PagerMaid-Pyro#36]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

最新版

### 运行环境

Linux

### 重现步骤

直接docker compose 安装提示 sh: 0: cannot open utils/docker-config.sh: No such file
如果git 整个下载的话 又重复在 配置， 

生成配置文件中 . . .
api_id、api_hash 申请地址： https://my.telegram.org/
请输入应用程序 api_id：请输入应用程序 api_hash：请输入应用程序语言（默认：zh-cn）：语言设置为 简体中文
请输入应用程序地区（默认：China）：地区设置为 中国
请输入 Google TTS 语言（默认：zh-CN）：tts发音语言设置为 简体中文
下面进行程序运行。
请在账户授权完毕后，按 Ctrl + C 使 Docker 在后台模式下运行。
invalid literal for int() with base 10: ''
欢迎进入 PagerMaid-Pyro Docker 。
配置即将开始
不停重启不能进入命令行

### 期望的结果是什么？

如何正确安装？

### 实际的结果是什么？

如何正确安装？

**Comment by omg-xtao** [comment]
```wget https://raw.githubusercontent.com/TeamPGM/PagerMaid-Pyro/development/utils/docker.sh -O docker.sh && chmod +x docker.sh && bash docker.sh```
