### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by phpluo** [TeamPGM/PagerMaid-Pyro#59]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

最新版

### 运行环境

Ubuntu

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

我一登录pagerMaid—Pro TG就闪退 所有终端都退出了 是不是这个TG号不能继续用pagemaid了

### 期望的结果是什么？

我一登录pagerMaid—Pro TG就闪退 所有终端都退出了 是不是这个TG号不能继续用pagemaid了

### 实际的结果是什么？

我一登录pagerMaid—Pro TG就闪退 所有终端都退出了 是不是这个TG号不能继续用pagemaid了

### 简单的复现代码/链接（可选）

```python3
我一登录pagerMaid—Pro TG就闪退 所有终端都退出了 是不是这个TG号不能继续用pagemaid了
```

### 日志记录（可选）

```python3
我一登录pagerMaid—Pro TG就闪退 所有终端都退出了 是不是这个TG号不能继续用pagemaid了
```

### 补充说明（可选）

我一登录pagerMaid—Pro TG就闪退 所有终端都退出了 是不是这个TG号不能继续用pagemaid了

**Comment by ricky8955555** [comment]
@phpluo 此并非为 PagerMaid-Pyro 的 Bug 所导致的，不应该在此处提出 Issue。
本项目不承担关于 Telegram 账户问题的任何责任。（https://github.com/TeamPGM#%E5%85%8D%E8%B4%A3%E5%A3%B0%E6%98%8E）

**Comment by omg-xtao** [comment]
duplicate #55
