### ISSUE TITLE
英国的giffgaff卡，区号为+44的号码在部署的时候提示号码不正确。。。

### ISSUE THREAD

**Issue by hecarli555** [TeamPGM/PagerMaid-Pyro#64]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 以及 [Pull Request](https://github.com/TeamPGM/PagerMaid-Pyro/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![image](https://github.com/TeamPGM/PagerMaid-Pyro/assets/76683744/fc2bac0d-35f6-412e-a70d-ee1291fbf278)
英国的giffgaff卡，区号为+44的号码在部署的时候提示号码不正确。。。用的是Pagermaid-Pyro 脚本安装

**Comment by omg-xtao** [comment]
xtaolabs.com

**Comment by omg-xtao** [comment]
@hecarli555 一键脚本是坏的，跟号码无关

**Comment by hecarli555** [comment]
> @hecarli555 一键脚本是坏的，跟号码无关

那怎么我看朋友用的+86的号码就成功部署上了。。。。

**Comment by hecarli555** [comment]
换docker的一键脚本，到最后一步，二维码的时候刷不出来二维码，，，，，真是醉了

**Comment by hecarli555** [comment]
求大佬回复，我朋友是国内部署的，带翻墙能力，他用的docker一键脚本没问题，二维码能刷新出来，我用的首尔甲骨文amd的vps部署后二维码刷不出来，，，，这是什么情况？
