### ISSUE TITLE
[Bug]: 在web临时关闭插件提示：操作失败

### ISSUE THREAD

**Issue by ei0ch** [TeamPGM/PagerMaid-Pyro#66]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

1.4.2

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

在web本地插件页面临时关闭插件提示操作失败

### 期望的结果是什么？

关停不必要插件

### 实际的结果是什么？

提示插件失败

**Comment by AkkiaS7** [comment]
修复已经merge
