### ISSUE TITLE
[Bug]: 数据持久化不同步

### ISSUE THREAD

**Issue by iAmP1us** [TeamPGM/PagerMaid-Pyro#87]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

1.4.13

### 运行环境

Linux

### 运行架构

AMD64

### 重现步骤

正常流程使用Docker 版一键脚本：wget https://raw.githubusercontent.com/TeamPGM/PagerMaid-Pyro/development/utils/docker.sh -O docker.sh && chmod +x docker.sh && bash docker.sh
之后选择数据持久化：Y
输入我的宿主机目录之后出现问题

### 期望的结果是什么？

正常情况，宿主机持久化数据挂载目录和容器内同步。

### 实际的结果是什么？

宿主机和容器里的内容不同。举例，我修改宿主机中data_path/data/config.yml，比如在config.yml添加了app_id和app_hash并保存，但是进入容器里查看config.yml，app_id和app_hash还是空白。
![宿主机内查看](https://github.com/user-attachments/assets/f75c2899-8511-4284-99c6-009eccdcda92)
![容器内查看](https://github.com/user-attachments/assets/8cc70951-a93e-47f9-92eb-7ccfe1c4d65c)

**Comment by omg-xtao** [comment]
执行下 
```bash
docker inspect 容器id
```
查看是否存在
```json
"HostConfig": {
            "Binds": [
                "data_path/workdir:/pagermaid/workdir"
            ],
```
确定修改的是 `data_path/workdir/data/config.yml` ?
