### ISSUE TITLE
[Bug]: 使用命令无响应问题及依赖版本问题

### ISSUE THREAD

**Issue by feishi12121** [TeamPGM/PagerMaid-Pyro#88]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/TeamPGM/PagerMaid-Pyro/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### PagerMaid 版本 （或 Commit Id）

latest

### 运行环境

Linux

### 运行架构

AMD64

### 重现步骤

![11](https://github.com/user-attachments/assets/1007ee98-739f-458d-8ad1-8c1d63af9c52)
启动后在tg输入,help报如图错误
![10 4 0](https://github.com/user-attachments/assets/a824b3a7-2017-471c-93a3-71c0c605f2ee)
指定pip源（https://pypi.org/simple）拉取requirement的pillow11.0.0库，显示最高支持到10.4.0

### 期望的结果是什么？

能够正常输出

### 实际的结果是什么？

tg输入命令无响应，拉取pillow拉取不到

**Comment by omg-xtao** [comment]
pillow 11.0.0 只支持 python 3.9 及其以上版本。python 3.8 已于 2024-10-07 结束其生命周期。

解决方式：

1. 更新到 python 3.9 及其以上版本，重新安装依赖。（推荐）

2. 只更新核心 pyrogram 依赖，然后重启 PGP 。`pip install git+https://github.com/TeamPGM/pyrogram@1.5.1` 。此方法可能导致后续 `,update` 仍无法正常更新。
